import type {Metadata} from "next"
import {Geist, Geist_Mono} from "next/font/google"
import "./globals.css"
import {ThemeProvider} from "@/shadcn/components/ThemeProvider"
import {Toaster} from "@/shadcn/components/ui/sonner"
import Navbar from "@/app/_components/Navbar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "MultiDrive Index",
    description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang={"en"} className={"min-h-full h-full"} suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <div className={"h-full flex flex-col"}>
                <Navbar />
                <div className={"py-4 flex-grow flex flex-row justify-center"}>
                    <div className={"w-full max-w-320 px-8"}>
                        {children}
                    </div>
                </div>
            </div>
            <Toaster/>
        </ThemeProvider>
        </body>
        </html>
    )
}
